export const LOCATION_CHANGED = '@@router/LOCATION_CHANGE'

export const REQUEST_STORY_START = 'REQUEST_STORY_START'
export const REQUEST_STORY_SUCCESS = 'REQUEST_STORY_SUCCESS'
export const REQUEST_STORY_FAILURE = 'REQUEST_STORY_FAILURE'

export const REQUEST_STORY_COMMENTS_START = 'REQUEST_STORY_COMMENTS_START'
export const REQUEST_STORY_COMMENTS_SUCCESS = 'REQUEST_STORY_COMMENTS_SUCCESS'
export const REQUEST_STORY_COMMENTS_FAILURE = 'REQUEST_STORY_COMMENTS_FAILURE'
